services:
  prontus:
    build:
      context: .
      dockerfile: Dockerfile
    image: prontus:dev
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - prontus-dados:/opt/jboss/dados

volumes:
  prontus-dados: