CREATE SEQUENCE IF NOT EXISTS SEQ_PACIENTE
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PACIENTE (
    ID BIGINT NOT NULL,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO TIMESTAMP(0) NOT NULL,
    DATA_CADASTRO TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_PACIENTE PRIMARY KEY (ID)
);