WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE SEQUENCE SEQ_PACIENTE
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

CREATE TABLE PACIENTE (
                          ID NUMBER(19) NOT NULL,
                          NOME_COMPLETO VARCHAR2(255 CHAR) NOT NULL,
                          DATA_NASCIMENTO TIMESTAMP(0) NOT NULL,
                          DATA_CADASTRO TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                          DATA_ATUALIZACAO TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                          CONSTRAINT PK_PACIENTE PRIMARY KEY (ID)
);